### PR TITLE
Return message for numbers

### LINKED ISSUE #8: status(n) returns n if n is a number
The readme states
```javascript
status(403) // => 'Forbidden'
status('403') // => 'Forbidden'
```

But true output is
```javascript
status(403) // => 403
status('403') // => 403
```

### PR DESCRIPTION
**Pull request by MiniGod**
PR to fix #8

### CODE REVIEW

**Comment by dougwilson** [comment]
Unfortunately this is not backwards-compatible. We either need to fix the docs to reflect the actual code behavior or hold this for a major version bump.

**Comment by MiniGod** [comment]
That's up to you.

**Comment by dougwilson** [comment]
I'll hold this PR for a future major bump :) For now I've fixed the readme.

**Comment by MiniGod** [comment]
Sounds good to me :+1:

**Comment by dougwilson** [comment]
What do you think we should do if you call it like `status('400 apples')`?

**Comment by MiniGod** [comment]
Its invalid, so it should probably throw. Though that might be a little too strict, and complicate the implementation a bit.

**Comment by dougwilson** [comment]
Perhaps. I don't mind making a major version bump, but when I do, I want to correct as many API mistakes as possible :)

**Comment by dougwilson** [comment]
New major version is being generated now, so PR landing.

**Comment by dougwilson** [comment]
It looks like I'm not allowed to push to your fork, so in order for me to rebase and merge, it won't show as this PR is merged and just closed instead. If showing the PR was merged is important, you can always enable pushes (follow https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/#enabling-repository-maintainer-permissions-on-existing-pull-requests on this PR) and I can push up the rebase and then merge. Otherwise I can just close this PR after committing.

Just wanted to give a heads-up. No hurry if you wanted to do that; I don't plan until releasing anything until like next week or so.

**Comment by MiniGod** [comment]
Hey @dougwilson! I've enabled that for you now.

**Comment by MiniGod** [comment]
LGTM! :+1:

**Comment by dougwilson** [comment]
Hi @MiniGod thank you for sticking around during this "journey". Your contribution is now part of the upcoming 2.0 release. We are hard at work onboarding folks and cleaning up repos to get them into a state of quicker turn-around.

**Pull request merged**
